In [1]:
import numpy as np

Problem 1
===

Part a
---

I am adding these vectors together, then doing mod 2. This result is `u`

In [2]:
v = np.array([1, 0, 0, 1, 0, 1, 1, 0])
b = np.array([1, 1, 0, 0, 1, 1, 0, 0])

u = (v+b)%2
print(u)


[0 1 0 1 1 0 1 0]


Part b
---

In [3]:
t = (u + b)%2
print("u + b mod 2 is:")
print(t)
print()
print("Compared to v this is:")
print(t == v)

u + b mod 2 is:
[1 0 0 1 0 1 1 0]

Compared to v this is:
[ True  True  True  True  True  True  True  True]


Part c
---

This is the same as v. This makes sense since we are modding by 2, adding `b` has the equivalent effect of subtracting by `b`. So `u + b` will be the same as `u - b`, which is equal to `v`

Problem 2
===

Now, I am solving to find a linear recurrance. The list of 1's and 0's is found below. I can solve linear systems created from this data repeatedly until I get a suitable pattern

In [4]:
recurrence = [1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 
              1, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1,
              0, 1, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1,
              0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 1, 1,
              0, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 0, 1, 1,
              0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0]

Part a
---

I made 3 functions to help me. First is `get_matrix()`, which given a size will return the appropriate sized matrix. For example, if I do `get_matrix(2)` it will give me `[[x1, x2], [x2, x3]]` and `[x3, x4]`.

Once I have my matrix and the vector, I can do a linear solve. However I can't do `np.linalg.solve()` because I need it to be modulus 2. So I made my own solving function, `lin_solve()`, to do this.

Lastly, I wanted to test my answer. Once I solve, I can pass my coefficient vector into `test_coefs()` and it will check it against all of `recurrence`. If an element fails, then it will print out where it failed. If the coefficients solve the recurrence equation, then it will print "This works!"

Now that I have these three functions, the process is simple. Starting with size 2, I need to get my matricies from the recurrence. This is done with the `get_matrix()`. Then, I need to solve the Matrix problem, which is done with `lin_solve()`. I can check to make sure there was a solution (aka det != 0), before testing my coefficients with the `test_coefs()` function. If something fails along the way, I just increment the size. Once we make it to the end, we will get the message "This works!". This process can be automated, but I step through it manually to help see the math along the way, and for dramatic effect.

In [5]:
# Sets up for linear solve
def get_matrix(size):
    # A 2d array, gets slices from x to x + size
    M = [recurrence[x : x + size] for x in range(0, size)]
    M = np.array(M)   # Make it a numpy array

    # And get our q, just get the answer slice
    q = recurrence[size : size + size] 

    return (M, q)


# To solve, I first want to check the determinate. If my det == 0, then
# there will be no solution. It it's 1, I will solve the equation
# using the inverse
def lin_solve(M, q):
    detM = np.linalg.det(M)
    if detM != 0:
        # This is (Inv(M) * det(M))%2 dotted with q, then %2 again.
        # (Inv(M) * det(M))%2 gives the inverse in %2, dotting solves it
        return np.dot((np.linalg.inv(M) * detM)%2, q)%2
    else:
        # Our error message, letting us know no solution
        print("Determinate is zero!")


# A test. Given a size and vector of contstants, we can dot this to 
# see how far our recurrance equation takes us.
def test_coefs(size, cs):
    # Goes through starting at size until the end
    for i in range(size, len(recurrence)):
        # We check the dot. Dotting by [c1, c2,..., cn] will 
        # give the predicted value. Check to see if it matches
        if recurrence[i] != np.dot(recurrence[i - size : i], cs)%2:
            print("Failed, x" + str(i + 1) + " should be", recurrence[i],\
                 "but was", np.dot(recurrence[i - size: i], cs)%2)
            return
    # All worked, print success
    print("This works!")

In [6]:
# Here we are starting with size = 2
size = 2
M2, q2 = get_matrix(size)
cs2 = lin_solve(M2, q2)
cs2

array([1., 0.])

In [7]:
# That solved, so lets test
test_coefs(size, cs2)

Failed, x7 should be 0 but was 1.0


In [8]:
# Okay that failed... lets try 3
size = 3
M3, q3 = get_matrix(size)
cs3 = lin_solve(M3, q3)
cs3

Determinate is zero!


In [9]:
# So no solution, lets try it for 4
size = 4
M4, q4 = get_matrix(size)
cs4 = lin_solve(M4, q4)
cs4

Determinate is zero!


In [10]:
# Unlucky, lets try 5
size = 5
M5, q5 = get_matrix(size)
cs5 = lin_solve(M5, q5)
cs5

array([1., 1., 0., 1., 1.])

In [11]:
# Aha! Lets test
test_coefs(size, cs5)

Failed, x11 should be 1 but was 0.0


In [12]:
# Well, it went a little bit before failing, try 6
size = 6
M6, q6 = get_matrix(size)
cs6 = lin_solve(M6, q6)
cs6

array([1., 1., 0., 0., 1., 1.])

In [13]:
test_coefs(size, cs6)

This works!


We found our formula! So the linear recurrance follows the pattern:

> x<sub>i</sub> = (x<sub>i-6</sub> + x<sub>i-5</sub> + x<sub>i-2</sub> + x<sub>i-1</sub>) % 2

Part b
---

Since the linear recurrance was solved in 6 steps, we know that if the first 6 match, the rest of the pattern will match. So I can find the starting index that will match indexes 0-5. In other words, once `[1, 0, 1, 0, 1, 0]` is repeated, we found our period

In [14]:
for i in range(6, len(recurrence)):
    if recurrence[i : i + 6] == [1, 0, 1, 0, 1, 0]:
        print(i)

63


So our period is 63. I can quickly double check this by comparing the first 63 to the next 63

In [15]:
recurrence[0:62] == recurrence[63:125]

True