In [1]:
import numpy as np 
import copy

Problem 1
===

For this part, I have a payoff matrix `X` that I will be analyizing. First I will remove and dominated columns, then find the expectation of the game. Lastly, I will look for long term winning conditions for both the row and column player

Part a 
---

I need to remove all dominated rows in `X`. I made myself 2 functions that can quickly check what rows and columns are dominated. So I run these on X, and it seems there are no strategies to remove

In [2]:
letters = ["A", "B", "C", "D", "E", "F"]
# To remove rows, do a comparison
def remove_rows(a, letter):
    for i in range(0, a.shape[0] - 1):
        for j in range(i + 1, a.shape[0]):
            if (np.all(a[i] - a[j] <= 0)):
                print("Row", letter[j], "dominates row", letters[i])
            elif (np.all(a[i] - a[j] >= 0)):
                print("Row", letter[i], "dominates row", letter[j])

# And do a similar comparison to remove the columns
def remove_cols(a, letter):
    for i in range(0, a.shape[1] - 1):
        for j in range(i + 1, a.shape[1]):
            if (np.all(a[:,i] - a[:,j] >= 0)):
                print("Column", letter[j], "dominates column", letter[i])
            elif (np.all(a[:,i] - a[:,j] <= 0)):
                print("Column", letter[i], "dominates column", letter[j])

In [3]:
X = np.array([[4, -3, 1, 3, 6, 2], [5, 9, 3, 9, -5, 5], 
              [3, 8, 3, 5, 7, -7], [-9, 9, 7, 3, 2, 4], 
              [9, 4, 8, -1, 1, 1], [2, 4, -2, 2, 5, 9]])
remove_rows(X, letters)
remove_cols(X, letters)
X   

array([[ 4, -3,  1,  3,  6,  2],
       [ 5,  9,  3,  9, -5,  5],
       [ 3,  8,  3,  5,  7, -7],
       [-9,  9,  7,  3,  2,  4],
       [ 9,  4,  8, -1,  1,  1],
       [ 2,  4, -2,  2,  5,  9]])

Since my remove functions didn't print out anything, I don't have a dominating strategy


Part b
---

Next, I need to find the expectation of the game. Here, I will use `M` as my matrix with all dominated strategies removed. Since I will be doing this multiple times, I made a function that will take an nxn matirix `M`, and return to me 3 things.

> 1. The probability list for the row player to meet the game's expectation
> 2. The probability list for the column player to meet the game's expectation
> 3. The game's expectation

The first return value will be a list named `p`, the second will be list named `q`, and the last is a value E

In [4]:
def game_expect(M):
    one = np.ones((M.shape[0], 1)   )

    x = np.linalg.solve(M.T, one)   # The row solved against 1's
    y = np.linalg.solve(M, one)     # The col solved against 1's

    p = x/np.sum(x)
    q = y/np.sum(y)

    E = np.dot(M, q)[0,0]

    return (p, q, E)

In [5]:
px, qx, Ex = game_expect(X)
print("My expected value of the game is", np.round(Ex, decimals=5))
print("Since this is positive, it favors the row player")

My expected value of the game is 3.01289
Since this is positive, it favors the row player


Part c & d 
---

Now, I want to find the probability options that can guarantee the game expectation. I already have my `p` and `q`, and I didn't remove any rows or columns. So in this instance, 'p' is how to ensure the row player will meet the game expectation, and `q` is how the column player meets the expectation. I made a quick printing function for this, since I will need it for the other parts of this project as well

In [6]:
def print_prob(p, q):
    print("The row player's picks should be as follows:")
    for i, prob in enumerate(p):
        print(letters[i], "picked", np.round(prob, decimals=4) * 100, "% of the time")

    print()
    print("The column player's picks should be as follows:")
    for i, prob in enumerate(q):
        print(letters[i], "picked", np.round(prob, decimals=4) * 100, "% of the time")

In [7]:
print_prob (px, qx)

The row player's picks should be as follows:
A picked [35.81] % of the time
B picked [13.18] % of the time
C picked [5.15] % of the time
D picked [13.1] % of the time
E picked [18.44] % of the time
F picked [14.33] % of the time

The column player's picks should be as follows:
A picked [8.72] % of the time
B picked [3.33] % of the time
C picked [23.8] % of the time
D picked [22.5] % of the time
E picked [25.44] % of the time
F picked [16.21] % of the time


Problem 2
===

Now, I have another matrix `Y`, I want to do the same process too. So I will start with looking for dominated strategies, then expectation, and lastly how to garuentee the row or column player will win in the long run.

Part a
---

First, I can just call my above methods to see what rows and columns need to be removed

In [8]:
Y = np.array([[1, 8, 8, 6, 3, 8], [5, 5, 8, 9, 9, 9],
              [3, 3, 3, 4, 8, 7], [0, 2, 3, 3, 2, 5], 
              [7, 9, 4, 4, 6, 4], [5, 0, 3, 5, 7, 1]])

remove_rows(Y, letters)

Row A dominates row D
Row B dominates row C
Row B dominates row D
Row B dominates row F
Row C dominates row D


It seems that rows C, D, and F are all dominated, lets remove them. But I also want to add them to a list so I know where to add zeros back into later

In [9]:
Yrowsdel = copy.copy(letters)
Yrowsdel.remove('C')
Yrowsdel.remove('D')
Yrowsdel.remove('F')

Y = np.delete(Y, 2, 0)
# Since I have already deleted a row or two, I need to subtract 1 or 2 from 3 and 5 
# respectively so I am removing the right row
Y = np.delete(Y, 2, 0)
Y = np.delete(Y, 3, 0)

# And now to check the cols
remove_cols(Y, letters)

Column A dominates column B
Column C dominates column F
Column D dominates column F


So it seems in the columns, B and F are dominated. So lets remove those, and again remember what I deleted

In [10]:
Ycolsdel = copy.copy(letters)
Ycolsdel.remove('B')
Ycolsdel.remove('F')

Y = np.delete(Y, 1, 1)
# Again, sub 1 from 2 and 2 from 3 since I am deleting rows
Y = np.delete(Y, 4, 1)

# Check again to see what needs to be removed
remove_rows(Y, Yrowsdel)
remove_cols(Y, Ycolsdel)

Row B dominates row A


In [11]:
Yrowsdel.remove('A')

Y = np.delete(Y, 0, 0)
remove_rows(Y, Yrowsdel)
remove_cols(Y, Ycolsdel)

Column C dominates column D
Column C dominates column E
Column D dominates column E


In [12]:
Ycolsdel.remove('D')
Ycolsdel.remove('E')

# Now I need to remove column 2 and 3
Y = np.delete(Y, 2, 1)
Y = np.delete(Y, 2, 1)

remove_rows(Y, Yrowsdel)
remove_cols(Y, Ycolsdel)
# Since I have no output, this is the final array
Y

array([[5, 8],
       [7, 4]])

Part b
---

Now, Like above we are going to check the expectaion of the game. I made the function to get expected game value 

In [13]:
pytemp, qytemp, Ey = game_expect(Y)
pytemp = pytemp.tolist()
qytemp = qytemp.tolist()

print("My expected value of the game is", np.round(Ey, decimals=5))
print("Since this is positive, it favors the row player")

My expected value of the game is 6.0
Since this is positive, it favors the row player


Part c & d
---

Again, I already made functions to get `p` and `q`. So now to make it a probability vector for A through F, I need to insert 0's where applicable

In [14]:
py = []
for l in letters:
    if l in Yrowsdel:
        py.append(pytemp.pop(0))
    else:
        py.append(0)
qy = []
for l in letters:
    if l in Ycolsdel:
        qy.append(qytemp.pop(0))
    else:
        qy.append(0)
print_prob(py, qy)

The row player's picks should be as follows:
A picked 0 % of the time
B picked [50.] % of the time
C picked 0 % of the time
D picked 0 % of the time
E picked [50.] % of the time
F picked 0 % of the time

The column player's picks should be as follows:
A picked [66.67] % of the time
B picked 0 % of the time
C picked [33.33] % of the time
D picked 0 % of the time
E picked 0 % of the time
F picked 0 % of the time


Problem 3
===

Once again, I will be following the same strategy that we have done for the other 2 matricies. However this one, `Z`, has boundary cases, so I will have to keep that in mind. 

Part a
---

Lets use the same process to pick what rows and columns are dominated

In [15]:
Zletters = letters[0:3]
Z = np.array([[9, 8, 1], [6, 7, 7], [8, 8, 2]])

remove_rows(Z, Zletters)
remove_cols(Z, Zletters)

Column C dominates column B


In [16]:
Zcolsdel = copy.copy(Zletters)
Zcolsdel.remove('B')

# I can remove column 2, and try again
Z = np.delete(Z, 1, 1)
remove_rows(Z, Zletters)
remove_cols(Z, Zcolsdel)
Z

array([[9, 1],
       [6, 7],
       [8, 2]])

Part b
---

Again, I need to find the expectation of the game. However, this needs to be broken up into sub problems since it is not a square Matrix. So I have my 3 sub-matricies. The name is Z followed by the row they do **not** include. After I break it up, I once again need to check for dominating rows and columns.

In [17]:
Zc = Z[0:2]
Za = Z[1:3]
Zb = np.array([Z[0], Z[2]])

print("For Za:")
remove_rows(Za, Zletters)
remove_cols(Za, Zletters)
print()
print("For Zb:")
remove_rows(Zb, Zletters)
remove_cols(Zb, Zletters)
print()
print("For Zc:")
remove_rows(Zc, Zletters)
remove_cols(Zc, Zletters)
print()

For Za:

For Zb:
Column B dominates column A

For Zc:



In [18]:
# So Zb needs to have A removed
Zbrowsdel = copy.copy(Zletters)
Zbcolsdel = copy.copy(Zletters)
Zbcolsdel.remove('A')
Zbrowsdel.remove('B')   # I removed b (cause this is Zb), so remove it from letters

Zb = np.delete(Zb, 0, 1)

remove_rows(Zb, Zbrowsdel)
remove_cols(Zb, Zletters)

Row C dominates row A


In [19]:
# And now column B dominates column A, lets remove
Zbrowsdel.remove('A')

Zb = np.delete(Zb, 0, 0)

remove_rows(Zb, Zbrowsdel)
remove_cols(Zb, Zbcolsdel)
Zb

array([[2]])

Since there is only 1 value left, this is the expected game value of Zb. Now I can use my other functions to get the expected game value of Za and Zc

In [20]:
pza, qza, Eza = game_expect(Za)
pzc, qzc, Ezc = game_expect(Zc)

print("My expected value of Za is", np.round(Eza, decimals=5))
print()
print("My expected value of Zc is", np.round(Ezc, decimals=5))

My expected value of Za is 6.28571

My expected value of Zc is 6.33333


Now, because the row player gets to pick on what subgame is played (because there are more rows then columns) he will want to maximize the game value. So he would go with Zc, or remove the C row from his playing pool.

Part c & d
---

I can now use this to find the probability for `pz` and `pq`. I already found `pzc` and `qzc`, so I just have to and 0's where appropriate

In [21]:
Zrowsdel = copy.copy(Zletters)
Zrowsdel.remove('C')   # Remove C since that was our boundary case
pztemp = pzc.tolist()
qztemp = qzc.tolist()

pz = []
for l in letters:
    if l in Zrowsdel:
        pz.append(pztemp.pop(0))
    else:
        pz.append(0)
qz = []
for l in letters:
    if l in Zcolsdel:
        qz.append(qztemp.pop(0))
    else:
        qz.append(0)
print_prob(pz, qz)

The row player's picks should be as follows:
A picked [11.11] % of the time
B picked [88.89] % of the time
C picked 0 % of the time
D picked 0 % of the time
E picked 0 % of the time
F picked 0 % of the time

The column player's picks should be as follows:
A picked [66.67] % of the time
B picked 0 % of the time
C picked [33.33] % of the time
D picked 0 % of the time
E picked 0 % of the time
F picked 0 % of the time
